config_map:   
  - name: PRODUCT
    value: "{{ product.name }}"  
  - name: JAEGER_SERVICE_NAME
    value: "{{ project }}-{{ microservice.name }}"
  - name: JAEGER_SAMPLER_TYPE
    value: const
  - name: JAEGER_SAMPLER_PARAM
    value: 1
  - name: JAEGER_SAMPLER_MANAGER_HOST_PORT
    value: "jaeger-agent.boost-services.svc:5778"    
  - name: JAEGER_AGENT_HOST
    value: "jaeger-agent.boost-services.svc"  
  - name: GATEWAY_API_SERVICE_URI
    value: "http://gateway-api.boost-services.svc:8080"     